### PR TITLE
Saver UX around exiting edit mode.

### LINKED ISSUE #12310: Editmode removed a day of work
### Version

0.19.1

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

I think i was in resolve mode, trying to resolve a conflict. I logged off and the next day i forgot about it. Did a lot of work and then opened gitbutler and saw edit mode. I didnt know what it was and clicked it away. All my work was gone and i couldnt even see it in the history. 

### How to reproduce (Optional)

1. Create a change
2. Make sure it is a conflict with the server
3. Go in resolve mode
4. Make extra changes and then go out of resolve mode

Im not a 100% sure that is what happened, but that is my best guess

### Expected behavior (Optional)

_No response_

### Relevant log output (Optional)

```shell

```

### PR DESCRIPTION
**Pull request by Caleb-T-Owens**
* Resolves https://github.com/gitbutlerapp/gitbutler/issues/12310

When exiting edit mode, the intended behaviour is that any changes made are dropped.

This, however, introduced a UX issue where users were not made aware this was the case, and it unfortunately resulted in one user losing work.

This commit introduces flows that inform users of the potential risk, suggest that saving and exiting may be the preferred action, and then provide a safety override.

I have not switched over to `safe_checkout` yet because I am not sure it is doing exactly what we need here. In general, I am keen to refactor this code to use the new commit engine and move away from the older usage of stacks. This code has not seen many updates over its lifetime.

---

Desktop UX:
If it's safe, abort is immediately performed, otherwise the following modal is shown:

Screenshot 2026-02-18 at 13 01 12

CLI UX:
If it's safe, abort is immediately performed, otherwise this message is shown:

```bash
X why > /Users/calebowens/Sherman/projects/gitbutler-client/target/debug/but resolve cancel
Initiated a background sync...
Failed to handle conflict resolution. There are changes that differ from the original commit you were editing. Canceling will drop those changes.

If you want to go through with this, please re-run with `--force`.

If you want to keep the changes you have made, consider finishing the resolution and then moving the changes with the rub command
```

### CODE REVIEW

File: crates/but/tests/but/command/resolve.rs [hunk 1]
```diff
@@ -116,3 +116,36 @@ fn resolve_cancel_works_in_edit_mode() -> anyhow::Result<()> {
...
+    let force_cancel_output = env.but("resolve cancel --force").output()?;
+    let force_cancel_stderr = String::from_utf8_lossy(&force_cancel_output.stderr);
+    anyhow::ensure!(
+        force_cancel_output.status.success(),
+        "resolve cancel --force should succeed"
+    );
+    anyhow::ensure!(
+        !force_cancel_stderr.contains("Setup required:"),
+        "resolve cancel --force should not fail setup checks"
+    );
```
Comment (Byron) [inline crates/but/tests/but/command/resolve.rs:147]: I noticed that AI really doesn't like Snapbox - it did this to me too and it's trivial to use snapbox here.

Can you fix it and maybe let it write instructions while at it?

File: crates/but/tests/but/command/resolve.rs [hunk 2]
```diff
@@ -116,3 +116,36 @@ fn resolve_cancel_works_in_edit_mode() -> anyhow::Result<()> {
...
+        "resolve cancel should fail without force"
+    );
+    anyhow::ensure!(
+        cancel_stderr.contains("--force"),
+        "resolve cancel without force should explain how to proceed; stderr was: {cancel_stderr}"
+    );
+
+    let force_cancel_output = env.but("resolve cancel --force").output()?;
+    let force_cancel_stderr = String::from_utf8_lossy(&force_cancel_output.stderr);
+    anyhow::ensure!(
```
Comment (Byron) [inline crates/but/tests/but/command/resolve.rs:140]: `anyhow::ensure!` is new to me as tests should panic, for the line numbers.

**Review by Byron — APPROVED** [review]
Thanks a lot, so much better!

Despite the approval for convenience, I'd really love that `but` test to be improved before a merge.
Thank you

**Comment by Caleb-T-Owens** [comment]
The tests were written using the existing pattern in that test file. I'll make a follow up PR that updates the testing tooling for this file.

**Comment by Byron** [comment]
Nevermind then, and thanks for making me aware. I will take a look and see if Agents.md can be adjusted to nudge future agents.
