### PR TITLE
Set gitHostFactory for gitlab self hosted instances

### LINKED ISSUE #4558: Branch button no longer opens branch in browser
### Version

0.12.16

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Usually the button `origin/<branch-name>` would open a new tab on my browser to my branch inside of my repository. Now it seems to no longer work.

Clicking on the button doesn't do anything. Maybe coming from the last update or the one before that. Only notice it this week.

Screenshot 2024-07-31 at 15 00 49

### How to reproduce

Apply branch that has an remote branch and try to click the button.

### Expected behavior

Clicking on the button should open a web page to the repository in the correct branch

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by fgLouro**
## ☕️ Reasoning
The `DefaultGitHostFactory` class assumes that gitlab domain is always `gitlab.com`, which is not correct for self hosted instances of gitlab, and leads to branch link buttons to be unusable. 

## 🧢 Changes
- Adds `resource` to `RepoInfo` type to be used for adding the correct `baseUrl`
- Checks `resource` for gitlab subdomain to initialize the `gitHostFactory` with a Gitlab class

## 🎫 Affected issues

Fixes: https://github.com/gitbutlerapp/gitbutler/issues/4558#issuecomment-2293337474

## Things to consider
Self hosted instance might not have `gitlab` in their subdomain, which will result in the same issue.

### CODE REVIEW

File: apps/desktop/src/lib/gitHost/gitHostFactory.ts [hunk 1]
```diff
@@ -36,7 +37,7 @@ export class DefaultGitHostFactory implements GitHostFactory {
 				usePullRequestTemplate
 			});
 		}
-		if (source.includes(GITLAB_DOMAIN)) {
+		if (source.includes(GITLAB_DOMAIN) || resource.includes(GITLAB_SUB_DOMAIN)) {
```
Comment (mtsgrd) [inline apps/desktop/src/lib/gitHost/gitHostFactory.ts]: Thanks for contributing! :)

Would it also be a good idea to make it stricter like this?
```ts
if (source === GITLAB_DOMAIN || resource.startsWith(GITLAB_SUB_DOMAIN + ".")) {
```
The current code is incorrect in that e.g. `agitlab.com` would be recognised as GitLab.

Comment (fgLouro) [reply apps/desktop/src/lib/gitHost/gitHostFactory.ts]: Makes sense

File: apps/desktop/src/lib/gitHost/gitlab/gitlab.ts [hunk 2]
```diff
@@ -1,13 +1,14 @@
-import { GitLabBranch } from './gitlabBranch';
 import type { RepoInfo } from '$lib/url/gitUrl';
 import type { GitHost } from '../interface/gitHost';
 import type { DetailedPullRequest, GitHostArguments } from '../interface/types';
+import { GitLabBranch } from './gitlabBranch';
```
Comment (ndom91) [inline apps/desktop/src/lib/gitHost/gitlab/gitlab.ts:4]: Well this now assumes that folks are putting their Gitlab instance at `gitlab.company.com` always, right?

What do you think about makign this a user setting? @mtsgrd

File: apps/desktop/src/lib/gitHost/gitlab/gitlab.ts [hunk 3]
```diff
@@ -1,13 +1,14 @@
...
 
 export type PrAction = 'creating_pr';
 export type PrState = { busy: boolean; branchId: string; action?: PrAction };
 export type PrCacheKey = { value: DetailedPullRequest | undefined; fetchedAt: Date };
 
 export const GITLAB_DOMAIN = 'gitlab.com';
+export const GITLAB_SUB_DOMAIN = 'gitlab'; // For self hosted instance of Gitlab
```
Comment (ndom91) [inline apps/desktop/src/lib/gitHost/gitlab/gitlab.ts:11]: Well this now assumes that folks are putting their Gitlab instance at `gitlab.company.com` always, right?

What do you think about makign this a user setting? @mtsgrd

Comment (mtsgrd) [reply apps/desktop/src/lib/gitHost/gitlab/gitlab.ts:11]: I was thinking this is a change in the right direction, even if we want to make it explicitly configurable? Aside from that, I do think we should start prioritising integration work, both building out our GH support, as well as building real integrations for the rest.

**Review by mtsgrd — APPROVED** [review]

File: apps/desktop/src/lib/gitHost/gitlab/gitlab.ts (hunk 3 above)
Comment (fgLouro) [reply apps/desktop/src/lib/gitHost/gitlab/gitlab.ts:11]: > Well this now assumes that folks are putting their Gitlab instance at gitlab.company.com always, right?

Yes, this is one issue. The better solution would be to have some setting where the user could define this in case the git url is different.

File: apps/desktop/src/lib/gitHost/github/githubBranch.test.ts [hunk 4]
```diff
@@ -8,7 +8,8 @@ describe.concurrent('GitHubBranch', () => {
 	const repo = {
 		source: 'github.com',
 		name: 'test-repo',
-		owner: 'test-owner'
+		owner: 'test-owner',
+		resource: 'test-resource'
```
Comment (mtsgrd) [inline apps/desktop/src/lib/gitHost/github/githubBranch.test.ts]: Let's not add these unless necessary for the test to pass?

File: apps/desktop/src/lib/url/gitUrl.ts [hunk 5]
```diff
@@ -4,20 +4,22 @@ export type RepoInfo = {
 	source: string;
 	name: string;
 	owner: string;
+	resource: string;
```
Comment (mtsgrd) [inline apps/desktop/src/lib/url/gitUrl.ts]: And make this optional?

Comment (fgLouro) [reply apps/desktop/src/lib/url/gitUrl.ts]: Wouldn't it be misleading to use an optional attribute for the `resource`? 

The `gitUrlParse` function seems to always return a `resource` attribute when the url is valid, even if it's an empty 'resource' it's not undefined.

Comment (mtsgrd) [reply apps/desktop/src/lib/url/gitUrl.ts]: Sorry, I forgot what it represents, and sorry for the back and forth here. I think.. we should only have one field for url, instead of calling it source and resource. If you agree, would you mind creating a type and replacing the one we borrow from the parsing lib?

Comment (fgLouro) [reply apps/desktop/src/lib/url/gitUrl.ts]: Back and forth is how good software is made 😄 

You mean removing the `resource` and `source` from the `RepoInfo` type and have only a `url` attribute which will be the value of `resource` (the full url)?

I think the `source` is only used in `DefaultGitHostFactory` class, so should be easy to replace it.

Comment (mtsgrd) [reply apps/desktop/src/lib/url/gitUrl.ts]: Yes, exactly! I would probably go with `domain` over `url` since it is likely to have additional things like scheme, path, etc. Also, my previous message was probably confusing because I forgot we have our own `RepoInfo` type, I thought we were using the one returned from `git-url-parse`.

Comment (fgLouro) [reply apps/desktop/src/lib/url/gitUrl.ts]: @mtsgrd Done!

Removed all references of `source` and `resource` in favour or using domain.

**Review by mtsgrd — APPROVED** [review]
A'ight, awesome. Let's ship it!
