### PR TITLE
fix 5099

### LINKED ISSUE #5099: [BUG] Can't open submodules as projects
### Version

0.13.0

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

I want to open and work in a submodule in my repo, but I get "Not a directory (os error 20)" when trying to open a submodule as a project. Opening the main project does not cause this issue.

### How to reproduce

Using the [cosmic-epoch](https://github.com/pop-os/cosmic-epoch) repo as an example

1. Clone https://github.com/pop-os/cosmic-epoch.
2. Init the submodules with `git submodule update --init --recursive`
3. Open any of the submodules inside the cosmic-epoch project as a submodule. It will throw the error.

### Expected behavior

**It should be able to open it** (i.e. deal with `.git` files)

### Relevant log output

```shell
2024-10-11T04:45:57.632111Z ERROR get_project: crates/gitbutler-project/src/controller.rs:161: failed to create "/home/jorge/rust_projects/cosmic-epoch/cosmic-applibrary/.git/gitbutler" on project get project_id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 error=Os { code: 20, kind: NotADirectory, message: "Not a directory" } id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 no_validation=None
2024-10-11T04:45:57.632145Z  INFO get_project: crates/gitbutler-tauri/src/projects.rs:32: close time.busy=804µs time.idle=47.3µs id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 no_validation=None
2024-10-11T04:45:57.633198Z ERROR set_project_active: crates/gitbutler-project/src/controller.rs:161: failed to create "/home/jorge/rust_projects/cosmic-epoch/cosmic-applibrary/.git/gitbutler" on project get project_id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 error=Os { code: 20, kind: NotADirectory, message: "Not a directory" } id=5bcdae24-6a01-4275-90d7-b9b5671a4a42
2024-10-11T04:45:57.633231Z ERROR set_project_active:set_project_to_window: crates/gitbutler-tauri/src/window.rs:129: error=Not a directory (os error 20) id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 window="main"
2024-10-11T04:45:57.633242Z  INFO set_project_active:set_project_to_window: crates/gitbutler-tauri/src/window.rs:129: close time.busy=19.7µs time.idle=6.48µs id=5bcdae24-6a01-4275-90d7-b9b5671a4a42 window="main"
2024-10-11T04:45:57.633252Z ERROR set_project_active: crates/gitbutler-tauri/src/projects.rs:67: error=Error(Not a directory (os error 20)) id=5bcdae24-6a01-4275-90d7-b9b5671a4a42
2024-10-11T04:45:57.633261Z  INFO set_project_active: crates/gitbutler-tauri/src/projects.rs:67: close time.busy=318µs time.idle=9.24µs id=5bcdae24-6a01-4275-90d7-b9b5671a4a42
```

### PR DESCRIPTION
**Pull request by Byron**
Add another check to assure folders without a `.git` directories aren't accepted.

Fixes #5099

### Tasks

* [x] reproduce
* [x] fix
* [x] fix in `gitoxide` for repo-classification (unrelated issue, actually)
* [x] use latest `main` of `gitoxide`

### Notes for the Reviewer

* I took the liberty and changed the integration test layout to the 'new' style that I have been adopting over at `gitoxide` as well. It leads to cleaner directories layouts in `tests/` and is overall easier to work with.
Here is a more elaborate example for that:
    - [before](https://github.com/Byron/gitoxide/tree/0cac69077e738cb22914e77a9a9dd3fd712d5670/gix/tests)
    - [after](https://github.com/Byron/gitoxide/tree/main/gix/tests)

### CODE REVIEW

File: crates/gitbutler-branch-actions/src/branch.rs [hunk 1]
```diff
@@ -481,7 +481,7 @@ pub fn get_branch_listing_details(
     let mut enriched_branches = Vec::new();
     let (diffstats, merge_bases) = {
         let (start, start_rx) = std::sync::mpsc::channel::<(
-            std::sync::mpsc::Receiver<gix::object::tree::diff::ChangeDetached>,
+            std::sync::mpsc::Receiver<gix::diff::tree_with_rewrites::Change>,
```
Comment (Byron) [inline crates/gitbutler-branch-actions/src/branch.rs]: I don't particularly love this and will probably re-introduced the `ChangeDetached` type as alternative name for this.

**Review by Caleb-T-Owens — APPROVED** [review]
Looks good to me, thanks!
