### PR TITLE
Don't do anything when dropping a commit onto itself

### LINKED ISSUE #6029: Dragging and dropping commit in a lane to the same spot raises error
### Version

0.14.6

### Operating System

macOS

### Distribution Method

dmg (Mac OS - Apple Silicon)

### Describe the issue

Image

### How to reproduce (Optional)

Drag and drop commit on a lane without moving it anywhere. Just to the same spot.

### Expected behavior (Optional)

_No response_

### Relevant log output (Optional)

```shell

```

### PR DESCRIPTION
**Pull request by Caleb-T-Owens**
* Closes https://github.com/gitbutlerapp/gitbutler/issues/6029

### CODE REVIEW

**Review by krlvi — APPROVED** [review]
Brilliant, thanks!

File: crates/gitbutler-branch-actions/src/squash.rs [hunk 1]
```diff
@@ -192,6 +192,13 @@ fn validate(
     source_commits: &[git2::Commit<'_>],
     destination_commit: &git2::Commit<'_>,
 ) -> Result<()> {
+    if source_commits
```
Comment (Byron) [inline crates/gitbutler-branch-actions/src/squash.rs:195]: If there are multiple commits A, B, C, could I not say to squash it all into `B`? This seems not unreasonable.

Comment (Caleb-T-Owens) [reply crates/gitbutler-branch-actions/src/squash.rs:195]: Why should B be a source AND the destination?

Comment (Caleb-T-Owens) [reply crates/gitbutler-branch-actions/src/squash.rs:195]: Should you not say you're squashing A and C into B?

Comment (Byron) [reply crates/gitbutler-branch-actions/src/squash.rs:195]: Ah, right, so that source commits never contain the destination. Yes, that's fair.
Since the user is making the selections though, maybe we could auto-correct what's correctable? Either in the frontend or in the backend?
