### PR TITLE
fix 4389

### LINKED ISSUE #4389: git fetch fails silently unless an ssh master process is started from CLI
### Version

0.12.10

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Hello, I'm running git CLI over SSH using either 1password or https://github.com/FiloSottile/yubikey-agent

Because I was using GB before it supported the execution of the git executable I was still using the self-generated keys.

Since the drop of that feature (no longer self-generated keys from GB) I have very weird behaviour.

- If I try to refresh the project trunk by clicking the ↺ icon, nothing hapens, like if there are no changes to fetch
- If I try to push, I got an error
- If I try to test credentials I get the following error

image

However, it I open a shell and run `git fetch` I get the 1password prompt for my ssh keys and from that point on, until the ssh master process expires its connection, I have a working GB (push and pull work as expected).

### How to reproduce

_No response_

### Expected behavior

If fetching fails, the UI should tell us.

I also would like to be able have this working without the need of a shell to run the first fetch operation.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Byron**
This PR fixes #4389 by causing loud errors in the backend if a remote failed to fetch, and selectively ignoring them when a background fetch is performed.
That way, the original behaviour is kept while showing errors on user action.

### Tasks

* [x] reproduce the issue
* [x] fix it
* [x] validate it's fixed and we see error messages only on explicit user action

### How to reproduce the original bug

* open a project that is cloned via SSH and setup a password protected SSH key
* trigger a fetch using the refresh button
* cancel the popup that asks for a password, possibly multiple times, until it gives up and errors

With this PR, the error is visible, without it is isn't.

### CODE REVIEW

File: app/src/lib/baseBranch/baseBranchService.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export class BaseBranchService {
 				return;
 			} else if (err.code === Code.ProjectsGitAuth) {
 				showError('Failed to authenticate', err);
-			} else {
+			} else if (action !== undefined) {
```
Comment (Byron) [inline app/src/lib/baseBranch/baseBranchService.ts:48]: This causes the frontend to not how errors when background fetches are performed.

File: crates/gitbutler-tauri/src/virtual_branches.rs [hunk 2]
```diff
@@ -478,12 +478,16 @@ pub mod commands {
...
             .update(&projects::UpdateRequest {
                 id: project.id,
-                project_data_last_fetched: Some(project_data_last_fetched),
+                project_data_last_fetched: Some(project_data_last_fetched.clone()),
                 ..Default::default()
             })
             .await
             .context("failed to update project with last fetched timestamp")?;
 
+        if let FetchResult::Error { error, .. } = project_data_last_fetched {
```
Comment (Byron) [inline crates/gitbutler-tauri/src/virtual_branches.rs:487]: This allows the frontend to respond to errors during fetching, which otherwise would have been swallowed here.

**Review by krlvi — APPROVED** [review]

**Comment by krlvi** [comment]
nice, thanks for fixing this @Byron!
