### PR TITLE
Eliminate ambiguity in unassigned area ID

### LINKED ISSUE #11219: Handle the case when 00 is ambiguous
If a branch contains "00" in it's refname, then rub operations involving the unassigned area (`00`) are ambiguous.

> but rub c0 00
> Rubbed the wrong way. Target '00' is ambiguous. Matches: xd (branch 'refactoring/BAC-00000_declerative_alfa_take_two'), 00 (the unassigned area). Try using more characters, a longer SHA, or the full branch name to disambiguate.
> Error: Rubbed the wrong way.
> 
> Caused by:
>     Target '00' is ambiguous. Matches: xd (branch 'refactoring/BAC-00000_declerative_alfa_take_two'), 00 (the unassigned area). Try using more characters, a longer SHA, or the full branch name to disambiguate.

https://discord.com/channels/1060193121130000425/1206670506271707156/1438480788621361242

### PR DESCRIPTION
**Pull request by jonathantanmy2**
## 🧢 Changes

Allow any number of 0s to refer to the unassigned area, and in `status`, print the minimum number of `0`s needed to disambiguate (for now, just against branch names).

See transcript below (for the `status` part).

```
[jt@archlinux gitoxide]$ but status
Initialized GitButler project from .. The default target is origin/main
╭┄00 [Unassigned Changes]
┊
┴ dba337d (common base) [origin/main] 2025-11-11 Merge pull request #2254 from ralphmodales/credent
[jt@archlinux gitoxide]$ but branch new b00
Created branch b00
[jt@archlinux gitoxide]$ but status
╭┄000 [Unassigned Changes]
┊
┊╭┄ux [b00] (no commits)
├╯
┊
┴ dba337d (common base) [origin/main] 2025-11-11 Merge pull request #2254 from ralphmodales/credent
```

## ☕️ Reasoning

Fixes bug (see Affected issues below) and this is also the start of centralizing CLI ID generation and interpretation, which allows better management of ambiguity (one such example is in this PR).

## 🎫 Affected issues

Fixes: #11219

### CODE REVIEW

File: crates/but/src/id.rs [hunk 1]
```diff
@@ -1,9 +1,39 @@
...
 use gitbutler_command_context::CommandContext;
 
+pub struct IdDb {
+    unassigned: CliId,
+}
+
+impl IdDb {
+    pub fn new(ctx: &CommandContext) -> anyhow::Result<Self> {
+        let mut max_zero_count = 1; // Ensure at least two "0" in ID.
+        let stacks = crate::log::stacks(ctx)?;
```
Comment (Byron) [inline crates/but/src/id.rs:15]: I see now that feature-gating the binary behind a `legacy` feature will be required to prevent usage like this to proliferate. The tell here is `gitbutler_command_context`, which is still spread throughout the codebase, and keeps spreading.

I will work on making this harder 😅, while offering alternatives.

**Review by Byron — APPROVED** [review]
Thanks a lot for contributing!

I'd merge this as it immediately fixes an issue, but would hope that with follow-up improvements to the CliIDs we can make itself more testable, for more isolated tests that don't have to invoke the whole binary.

CC @krlvi for another look as well.

**Comment by krlvi** [comment]
Thanks for fixing this!
