### PR TITLE
Fix Signing

### LINKED ISSUE #5839: SSH: Unable to find program
### Version

0.14.4

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Using 1password as my ssh agent. Was working until I updated to latest version: 

SSH agent path: C:\Program Files\1Password\app\8\op-ssh-sign.exe
Confirmed it exists, is working for other programs

### How to reproduce

_No response_

### Expected behavior

Should sign commits. 

### Relevant log output

```shell
Program not found
user.C034edPS.js:4 
 ipc->check_signing_settings: {"id":"31d6e997-0f4b-4b08-8a9a-e666c46c1609"} s: Program not found
    at s.fromError (http://tauri.localhost/_app/immutable/chunks/ipc.DM3tJdKb.js:1:1093)
    at w (http://tauri.localhost/_app/immutable/chunks/ipc.DM3tJdKb.js:1:1297)
    at async Object.C [as onclick] (http://tauri.localhost/_app/immutable/nodes/27.0QkJqKa9.js:10:818) 
Object
user.C034edPS.js:4 
 Error checking signing: s: Program not found
    at s.fromError (http://tauri.localhost/_app/immutable/chunks/ipc.DM3tJdKb.js:1:1093)
    at w (http://tauri.localhost/_app/immutable/chunks/ipc.DM3tJdKb.js:1:1297)
    at async Object.C [as onclick] (http://tauri.localhost/_app/immutable/nodes/27.0QkJqKa9.js:10:818)
(anonymous)	@	user.C034edPS.js:4
```

### PR DESCRIPTION
**Pull request by Byron**
### Tasks

* [x] Debugging tool for environment variables
* [x] path-quoting for the command itself
* [x] switch to gitoxide on `main`
* [x] test it for real once!

---
* Related to #5735
* Fixes #5839

### CODE REVIEW

**Comment by Caleb-T-Owens** [comment]
@Byron if the command has already been quoted, should we strip them out? For a short while the advice on discord and GH was to add them, but now they could be problematic?

**Comment by Byron** [comment]
The issue was that the command is now run as shell-command on Windows, which also means commands would need to be quoted to handle paths with spaces like `…/Program Files/…` correctly.
It's quite sad I didn't see that coming as well.

File: apps/desktop/src/routes/+layout.svelte [hunk 1]
```diff
@@ -160,6 +160,12 @@
 		// Toggle v3 design on/off
 		'v 3': () => {
 			settingsService.updateFeatureFlags({ v3: !$settingsStore?.featureFlags.v3 });
+		},
+		'e n v': async () => {
```
Comment (krlvi) [inline apps/desktop/src/routes/+layout.svelte:165]: Probably worth adding a comment that this only works in debug mode

File: crates/gitbutler-tauri/src/env.rs [hunk 2]
```diff
@@ -0,0 +1,7 @@
+use std::collections::BTreeMap;
+
+#[cfg(debug_assertions)]
```
Comment (krlvi) [inline crates/gitbutler-tauri/src/env.rs:3]: Probably worth adding a comment that this should not be removed (i.e we definitely do not want this in prod)

**Review by krlvi — APPROVED** [review]
