### PR TITLE
fix: use push direction for remote when checking for gerrit remote

### LINKED ISSUE #10908: Gerrit remote detection (and use) should use .remote_default_name(Direction::Push), not .remote_default_name(Direction::Fetch)
There might be situations like this, where a faster URL is used for fetching than for pushing:
```
❯ git remote show qt-project
* remote qt-project
  Fetch URL: git://code.qt.io/qt/qtbase.git
  Push  URL: ssh://codereview.qt-project.org/qt/qtbase.git
  HEAD branch: dev
```

Which the git porcelain handles automatically:
```
# Single URL repo
❯ git remote get-url --push qt-project
ssh://codereview.qt-project.org:/qt/qtbase

❯ git remote get-url qt-project
ssh://codereview.qt-project.org:/qt/qtbase

# Multi URL repo
❯ git remote get-url --push qt-project
ssh://codereview.qt-project.org/qt/qtbase.git

❯ git remote get-url qt-project
git://code.qt.io/qt/qtbase.git
```

So GB should do the equivalent of `git remote get-url --push` when dealing with Gerrit remotes.

### PR DESCRIPTION
**Pull request by krlvi**
fixes https://github.com/gitbutlerapp/gitbutler/issues/10908

### CODE REVIEW

File: crates/gitbutler-project/src/controller.rs [hunk 1]
```diff
@@ -333,15 +333,15 @@ pub fn is_gerrit_remote(repo: &gix::Repository) -> anyhow::Result<bool> {
     let gerrit_notes_ref = "refs/notes/review";
 
     let remote_name = repo
-        .remote_default_name(Direction::Fetch)
+        .remote_default_name(Direction::Push)
         .ok_or_else(|| anyhow::anyhow!("No fetch remotes found"))?;
```
Comment (cbjeukendrup) [inline crates/gitbutler-project/src/controller.rs]:
```suggestion
        .ok_or_else(|| anyhow::anyhow!("No push remotes found"))?;
```

**Comment by Byron** [comment]
The change that is performed to the remote isn't persisted, neither in memory nor on disk, so it really shouldn't have any effect.

However, when running the tests locally I have strange failures along the lines of 

```
  left: "create file\n\nChange-Id: I36a88dec809d837ab644485a62b3aa66c4296043\n"
 right: "create file"
```

And… I get it now: the new way of detection actually enables gerrit mode and that adds change-id trailers to commits the test-suite creates.

The mapping that's returned is:

```
[crates/gitbutler-project/src/controller.rs:347:5] &map = RefMap {
    mappings: [
        Mapping {
            remote: Ref(
                Direct {
                    full_ref_name: "refs/heads/main",
                    object: Sha1(9483946de825e4faf7c2597a2aa7db51c1fc3950),
                },
            ),
            local: Some(
                "refs/remotes/origin/main",
            ),
            spec_index: ExplicitInRemote(
                0,
            ),
        },
    ],
    refspecs: [
        RefSpec {
            mode: Force,
            op: Fetch,
            src: Some(
                "refs/heads/*",
            ),
            dst: Some(
                "refs/remotes/origin/*",
            ),
        },
    ],
    extra_refspecs: [],
    fixes: [],
    remote_refs: [
        Direct {
            full_ref_name: "refs/heads/main",
            object: Sha1(9483946de825e4faf7c2597a2aa7db51c1fc3950),
        },
    ],
    object_hash: Sha1,
}
```

So it seems the refspec replacement isn't working. 

The major problem for me is that the test-suite seems to trash the cache for the test itself, so each test-run recompiles half the world and feedback arrives only after ~50s.

With that said, the remote itself looks like it has the right push-refspecs:

```
---- complex_file_manipulation_multiple_hunks_with_uncommitted_changes stdout ----
[crates/gitbutler-project/src/controller.rs:342:20] remote.with_fetch_tags(gix::remote::fetch::Tags::None) = Remote {
    name: Some(
        Symbol(
            "origin",
        ),
    ),
    url: Some(
        Url {
            scheme: File,
            user: None,
            password: None,
            host: None,
            serialize_alternative_form: true,
            port: None,
            path: "/Users/byron/dev/github.com/gitbutlerapp/gitbutler/crates/gitbutler-branch-actions/tests/fixtures/generated-do-not-edit/dependencies/1407415208-unix/remote",
        },
    ),
    url_alias: None,
    push_url: None,
    push_url_alias: None,
    fetch_specs: [
        RefSpec {
            mode: Force,
            op: Fetch,
            src: Some(
                "refs/heads/*",
            ),
            dst: Some(
                "refs/remotes/origin/*",
            ),
        },
    ],
    push_specs: [
        RefSpec {
            mode: Normal,
            op: Push,
            src: Some(
                "refs/notes/review",
            ),
            dst: None,
        },
    ],
    fetch_tags: None,
    repo: Repository {
        kind: WorkTree {
            is_linked: false,
        },
        git_dir: "/Users/byron/dev/github.com/gitbutlerapp/gitbutler/crates/gitbutler-branch-actions/tests/fixtures/generated-do-not-edit/dependencies/1407415208-unix/complex-file-manipulation-multiple-hunks/.git",
        workdir: Some(
            "/Users/byron/dev/github.com/gitbutlerapp/gitbutler/crates/gitbutler-branch-actions/tests/fixtures/generated-do-not-edit/dependencies/1407415208-unix/complex-file-manipulation-multiple-hunks",
        ),
    },
}
```

The problem seems to be that the `connect(Push)` only choses the push remote server, but the `ref_map()` call still uses the fetch-specs.

The solution is to change the fetch-specs. With that, I get empty `remote_refs` in the failing test.

```
[crates/gitbutler-project/src/controller.rs:347:5] &map = RefMap {
    mappings: [],
    refspecs: [
        RefSpec {
            mode: Normal,
            op: Fetch,
            src: Some(
                "refs/notes/review",
            ),
            dst: None,
        },
    ],
    extra_refspecs: [],
    fixes: [],
    remote_refs: [],
    object_hash: Sha1,
}
```

The test, however, still fails as it seems to somehow think gerrit mode is enabled, even though that now returns false.

Somehow gerrit mode ends up enabled in the fixture repository:

```
[branch "main"]
        remote = origin
        merge = refs/heads/main
[gitbutler]
        gerritMode = true
[log]
        excludeDecoration = refs/gitbutler
```

And… the issue was that the test uses a read-only fixture, which has been altered in prior runs. Deleting the repository makes the test work, and CI should work as well now.

**Comment by krlvi** [comment]
Thanks for the help!

**Comment by Byron** [comment]
It's unfortunate that Gerrit detection still seems to produce false positives with certain Azure servers. They really are special, somehow.
